### ISSUE TITLE
Subscribe queue

### ISSUE THREAD

**Issue by tcury** [tcury/mail-express#2]
Install stomp gem to talk with ActiveMQ.
Subscribe to 'sending' queue. After receive messages mock to save to file or print to stdout/log.
Write unit test to publish to 'sending' queue.

**Comment by thalessr** [comment]
@tcury  the stomp gem seems that it does not receive a recent actualization as the last commit was a year ago.
https://github.com/stompgem/stomp
Will we use that gem?

**Comment by tcury** [comment]
@thalessr yes!
